language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
        env: TOXENV=py39
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3
install:
  - pip install tox 
script:
  - tox
