[testenv]
commands=
    pip install -e .
    pytest -p no:logging --cov=flask_moment --cov-branch --cov-report term-missing --cov-report=xml
deps=
    pytest
    pytest-cov

[testenv:flake8]
commands=
    flake8 src/flask_moment tests example
deps=
    flake8

[testenv:docs]
changedir=docs
deps=
    sphinx
allowlist_externals=
    make
commands=
    make html
